name: Minecraft Bot

on:
  workflow_dispatch:   # Chạy thủ công khi bấm nút
  push:                # Chạy khi push code

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install   # Không cần lock file nữa

      - name: Run Minecraft bot
        run: node index.js
